In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array ([
    [2, -1,  3, 4],
    [1,  0, -2, 7],
    [3, -3,  1, 5],
    [2,  1,  4, 4.]
])

print (A)

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]


In [3]:
b = np.array ([
    [ 9],
    [11],
    [ 8],
    [10.]
])

print (b)

[[ 9.]
 [11.]
 [ 8.]
 [10.]]


In [4]:
m, n = A.shape
print (m)

4


In [5]:
L = np.eye (m)
R = np.copy (A)
for i in range (m - 1):
    for j in range (i + 1, m):
        t = R [j, i] / R [i, i]
        L [j, i] = t
        for k in range (i, m):
            R [j, k] -= t * R [i, k]

print (L)
print ()
print (R)
print ()
print (L @ R)
print ()
print (A)
print ()
print (np.round (L @ R - A, 10))

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 1.5        -3.          1.          0.        ]
 [ 1.          4.         -1.07142857  1.        ]]

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]

[[ 2. -1.  3.  4.]
 [ 1.  0. -2.  7.]
 [ 3. -3.  1.  5.]
 [ 2.  1.  4.  4.]]

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -0.  0.]]


In [6]:
y = np.zeros ((m, 1))
for i in range (m):
    t = b [i, 0]
    for k in range (i):
        t -= L [i, k] * y [k, 0]
    y [i, 0] = t

print (L)
print ()
print (y)
print ()
print (L @ y)
print ()
print (b)
print ()
print (L @ y - b)

[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 1.5        -3.          1.          0.        ]
 [ 1.          4.         -1.07142857  1.        ]]

[[  9. ]
 [  6.5]
 [ 14. ]
 [-10. ]]

[[ 9.]
 [11.]
 [ 8.]
 [10.]]

[[ 9.]
 [11.]
 [ 8.]
 [10.]]

[[0.]
 [0.]
 [0.]
 [0.]]


In [7]:
x = np.zeros ((m, 1))
for i in range (m - 1, -1, -1):
    t = y [i, 0]
    for k in range (i + 1, m):
        t -= R [i, k] * x [k, 0]
    x [i, 0] = t / R [i, i]

print (R)
print ()
print (x)
print ()
print (R @ x)
print ()
print (y)
print ()
print (R @ x - y)

[[  2.   -1.    3.    4. ]
 [  0.    0.5  -3.5   5. ]
 [  0.    0.  -14.   14. ]
 [  0.    0.    0.   -5. ]]

[[-1.]
 [ 0.]
 [ 1.]
 [ 2.]]

[[  9. ]
 [  6.5]
 [ 14. ]
 [-10. ]]

[[  9. ]
 [  6.5]
 [ 14. ]
 [-10. ]]

[[0.]
 [0.]
 [0.]
 [0.]]
