# Lineare Algebra - SW 04 - Lösungen

In [1]:
import numpy as np
import numpy.linalg as la

## Aufgabe 1

$ \begin{align}
    \mathbf{A}
        &\;=\; \begin{pmatrix} 4 & 3 \\ 8 & 6 \end{pmatrix}
        \;; \qquad \mathrm{det} \, (\mathbf{A}) \;=\; 4 \cdot 6 - 8 \cdot 3 \;=\; 24 - 24 \;=\; 0
        \;; \qquad \mbox{$\mathbf{A}$ singulär, nicht invertierbar}
\end{align} $

In [2]:
A = np.array ([[4, 3], [8, 6]])
print (la.det (A))

0.0


$ \begin{align}
    \mathbf{B} 
        &\;=\; \begin{pmatrix} 4 & 3 \\ 8 & 7 \end{pmatrix} \;;
        \qquad \mathrm{det} \, (\mathbf{B}) \;=\; 4 \cdot 7 - 8 \cdot 3 \;=\; 28 - 24 \;=\; 4 \;;
        \qquad \mathbf{B}^{-1} \;=\; \frac{1}{4} \, \begin{pmatrix} 7 & -3 \\ -8 & 4 \end{pmatrix}
\end{align} $

In [3]:
B = np.array ([[4, 3], [8, 7]])
print (B)

[[4 3]
 [8 7]]


In [4]:
Bi = np.array ([[7, -3], [-8, 4]]) / 4.0
print (Bi)

[[ 1.75 -0.75]
 [-2.    1.  ]]


In [5]:
print (Bi @ B)
print (B @ Bi)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


$ \begin{align}
    \mathbf{C}
        &\;=\; \begin{pmatrix} 6 & 6 \\ 6 & 6 \end{pmatrix}
        \;; \qquad \mathrm{det} \, (\mathbf{C}) \;=\; 6 \cdot 6 - 6 \cdot 6 \;=\; 36 - 36 \;=\; 0
        \;; \qquad \mbox{$\mathbf{C}$ singulär, nicht invertierbar}
\end{align} $

In [6]:
C = np.array ([[6, 6], [6, 6]])
print (la.det (C))

0.0


$ \begin{align}
    \mathbf{D}
        \;=\; \begin{pmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 1 & 1 & 1 \end{pmatrix} \\
\end{align} $

$ \begin{align}
        \begin{pmatrix} 
            1 & 0 & 0 & 1 & 0 & 0 \\
            1 & 1 & 0 & 0 & 1 & 0 \\
            1 & 1 & 1 & 0 & 0 & 1 
        \end{pmatrix} 
        \;;\quad \begin{pmatrix}
            1 & 0 & 0 &  1 & 0 & 0 \\
            0 & 1 & 0 & -1 & 1 & 0 \\
            1 & 1 & 1 &  0 & 0 & 1
        \end{pmatrix}
        \;;\quad \begin{pmatrix}
            1 & 0 & 0 &  1 & 0 & 0 \\
            0 & 1 & 0 & -1 & 1 & 0 \\
            0 & 1 & 1 & -1 & 0 & 1
        \end{pmatrix}
        \;;\quad \begin{pmatrix}
            1 & 0 & 0 &  1 &  0 & 0 \\
            0 & 1 & 0 & -1 &  1 & 0 \\
            0 & 0 & 1 &  0 & -1 & 1
        \end{pmatrix}
\end{align} $

In [7]:
D = np.array ([[1, 0, 0], [1, 1, 0], [1, 1, 1]])
print (D)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [8]:
Di = np.array ([[1, 0, 0], [-1, 1, 0], [0, -1, 1]])
print (Di)

[[ 1  0  0]
 [-1  1  0]
 [ 0 -1  1]]


In [9]:
print (Di @ D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [10]:
print (D @ Di)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Aufgabe 2

$ \begin{align}
    \mathbf{A} 
        &\;=\; \begin{pmatrix} 0 & 3 \\ 4 & 0 \end{pmatrix}
\end{align} $

$ \begin{align}
    \begin{pmatrix} 0 & 3 & 1 & 0 \\ 4 & 0 & 0 & 1 \end{pmatrix}
        \;;\quad \begin{pmatrix} 4 & 0 & 0 & 1 \\ 0 & 3 & 1 & 0 \end{pmatrix}
\end{align} $

$\mathbf{A}$, direkt:

$ \begin{align}
    3 \, x_2 \;=\; 1 &\quad\Rightarrow\quad x_2 \;=\; \frac{1}{3} \\
    4 \, x_1 \;=\; 0 &\quad\Rightarrow\quad x_1 \;=\; 0 \\
    3 \, y_2 \;=\; 0 &\quad\Rightarrow\quad y_2 \;=\; 0 \\
    4 \, y_1 \;=\; 1 &\quad\Rightarrow\quad y_1 \;=\; \frac{1}{4} \\
\end{align} $

$ \begin{align}
    A ^{-1}
        \;=\; \begin{pmatrix} x_1 & y_1 \\ x_2 & y_2 \end{pmatrix}
        \;=\; \begin{pmatrix} 0 & \frac{1}{4} \\ \frac{1}{3} & 0 \end{pmatrix}
\end{align} $

$\mathbf{A}$, Gauss-Jordan:

$ \begin{align}
    \begin{pmatrix} 4 & 0 & 0 & 1 \\ 0 & 3 & 1 & 0 \end{pmatrix}
        \;;\quad \begin{pmatrix} 4 & 0 & 0 & 1 \\ 0 & 1 & \frac{1}{3} & 0 \end{pmatrix}
        \;;\quad \begin{pmatrix} 1 & 0 & 0 & \frac{1}{4} \\ 0 & 1 & \frac{1}{3} & 0 \end{pmatrix}
\end{align} $

$\mathbf{A}$, Python:

In [11]:
A0 = np.array ([[0, 3, 1, 0], [4, 0, 0, 1]])
print (A0)

[[0 3 1 0]
 [4 0 0 1]]


In [12]:
A1 = np.array ([A0 [1], A0 [0]])
print (A1)

[[4 0 0 1]
 [0 3 1 0]]


In [13]:
A2 = np.array ([A1 [0] / 4.0, A1 [1] / 3.0])
print (A2)

[[1.         0.         0.         0.25      ]
 [0.         1.         0.33333333 0.        ]]


In [14]:
A = A0 [0:2, 0:2]
print (A)

[[0 3]
 [4 0]]


In [15]:
Ai = A2 [0:2, 2:4]
print (Ai)

[[0.         0.25      ]
 [0.33333333 0.        ]]


In [16]:
print (Ai @ A)

[[1. 0.]
 [0. 1.]]


$ \begin{align}
    \mathbf{B} 
        &\;=\; \begin{pmatrix} 2 & 0 \\ 4 & 2 \end{pmatrix}
\end{align} $

$ \begin{align}
    \begin{pmatrix} 2 & 0 & 1 & 0 \\ 4 & 2 & 0 & 1 \end{pmatrix}
        \;;\quad \begin{pmatrix} 2 & 0 & 1 & 0 \\ 0 & 2 & -2 & 1 \end{pmatrix}
\end{align} $

$\mathbf{B}$, direkt:

$ \begin{align}
    2 \, x_2 \;=\; -2 &\quad\Rightarrow\quad x_2 \;=\; -1 \\
    2 \, x_1 \;=\; 1 &\quad\Rightarrow\quad x_1 \;=\; \frac{1}{2} \\
    2 \, y_2 \;=\; 1 &\quad\Rightarrow\quad y_2 \;=\; \frac{1}{2} \\
    2 \, y_1 \;=\; 0 &\quad\Rightarrow\quad y_1 \;=\; 0 \\
\end{align} $

$ \begin{align}
    \mathbf{B}^{-1}
        \;=\; \begin{pmatrix} x_1 & y_1 \\ x_2 & y_2 \end{pmatrix}
        \;=\; \begin{pmatrix} \frac{1}{2} & 0 \\ -1 & \frac{1}{2} \end{pmatrix}
\end{align} $

$\mathbf{B}$, Gauss-Jordan:

$ \begin{align}
    \quad \begin{pmatrix} 2 & 0 & 1 & 0 \\ 0 & 2 & -2 & 1 \end{pmatrix}
        \;;\quad \begin{pmatrix} 1 & 0 & \frac{1}{2} & 0 \\ 0 & 1 & -1 & \frac{1}{2} \end{pmatrix}
\end{align} $

$\mathbf{B}$, Python:

In [17]:
B0 = np.array ([[2, 0, 1, 0], [4, 2, 0, 1]])
print (B0)

[[2 0 1 0]
 [4 2 0 1]]


In [18]:
B1 = np.array ([B0 [0], B0 [1] - 2 * B0 [0]])
print (B1)

[[ 2  0  1  0]
 [ 0  2 -2  1]]


In [19]:
B2 = B1 / 2
print (B2)

[[ 1.   0.   0.5  0. ]
 [ 0.   1.  -1.   0.5]]


In [20]:
B = B0 [0:2, 0:2]
print (B)

[[2 0]
 [4 2]]


In [21]:
Bi = B2 [0:2, 2:4]
print (Bi)

[[ 0.5  0. ]
 [-1.   0.5]]


In [22]:
print (Bi @ B)

[[1. 0.]
 [0. 1.]]


$ \begin{align}
    \mathbf{C} 
        &\;=\; \begin{pmatrix} 3 & 4 \\ 5 & 7 \end{pmatrix}
\end{align} $


$ \begin{align}
    \begin{pmatrix} 3 & 4 & 1 & 0 \\ 5 & 7 & 0 & 1 \end{pmatrix}
        \;;\quad \begin{pmatrix} 15 & 20 & 5 & 0 \\ 15 & 21 & 0 & 3 \end{pmatrix}
        \;;\quad \begin{pmatrix} 3 & 4 & 1 & 0 \\ 0 & 1 & -5 & 3 \end{pmatrix}
\end{align} $

$\mathbf{C}$, direkt:

$ \begin{align}
    x_2 \;=\; -5 \\
    3 \, x_1 + 4 \, x_2 \;=\; 1 &\quad\Rightarrow\quad x_1 
        \;=\; \frac{1 - 4 \, x_2}{3}
        \;=\; \frac{1 + 20}{3}
        \;=\; 7
        \\
    y_2 \;=\; 3 \\
    3 \, y_1 + 4 \, y_2 \;=\; 0 &\quad\Rightarrow\quad y_1
        \;=\; \frac{- \, 4 \, y_2}{3}
        \;=\; -4
\end{align} $

$ \begin{align}
    \mathbf{C}^{-1}
        \;=\; \begin{pmatrix} x_1 & y_1 \\ x_2 & y_2 \end{pmatrix}
        \;=\; \begin{pmatrix} 7 & -4 \\ -5 & 3 \end{pmatrix}
\end{align} $

$\mathbf{C}$, Gauss-Jordan:

$ \begin{align}
    \begin{pmatrix} 3 & 4 & 1 & 0 \\ 0 & 1 & -5 & 3 \end{pmatrix}
        \;;\quad \begin{pmatrix} 3 & 4 & 1 & 0 \\ 0 & 4 & -20 & 12 \end{pmatrix}
        \;;\quad \begin{pmatrix} 3 & 0 & 21 & -12 \\ 0 & 4 & -20 & 12 \end{pmatrix}
        \;;\quad \begin{pmatrix} 1 & 0 & 7 & -4 \\ 0 & 1 & -5 & 3 \end{pmatrix}
\end{align} $

$\mathbf{C}$, Python:

In [23]:
C0 = np.array ([[3, 4, 1, 0], [5, 7, 0, 1]])
print (C0)

[[3 4 1 0]
 [5 7 0 1]]


In [24]:
C1 = np.array ([C0 [0], 3 * C0 [1] - 5 * C0 [0]])
print (C1)

[[ 3  4  1  0]
 [ 0  1 -5  3]]


In [25]:
C2 = np.array ([C1 [0] - 4 * C1 [1], C1 [1]])
print (C2)

[[  3   0  21 -12]
 [  0   1  -5   3]]


In [26]:
C3 = np.array ([C2 [0] / 3, C2 [1]])
print (C3)

[[ 1.  0.  7. -4.]
 [ 0.  1. -5.  3.]]


In [27]:
C = C0 [0:2, 0:2]
print (C)

[[3 4]
 [5 7]]


In [28]:
Ci = C3 [0:2, 2:4]
print (Ci)

[[ 7. -4.]
 [-5.  3.]]


In [29]:
print (Ci @ C)

[[1. 0.]
 [0. 1.]]


## Aufgabe 3

$ \begin{align}
    A 
        &\;=\; \begin{pmatrix} 1 & 2 \\ 3 & 6 \end{pmatrix}
\end{align} $

$ \begin{align}
    \begin{pmatrix} 1 & 2 \\ 3 & 6 \end{pmatrix} \;;
        \quad \begin{pmatrix} 3 & 6 \\ 3 & 6 \end{pmatrix} \;;
        \quad \begin{pmatrix} 1 & 2 \\ 0 & 0 \end{pmatrix} \;;
        \qquad \mbox{$\mathbf{A}$ singulär, nicht invertierbar}
\end{align} $

## Aufgabe 4

Wenn man eine Zeile einer Matrix $\mathbf{A}\in\mathbb{R}^{n\times{n}}$ mit $\lambda$
multipliziert, so wird auch die Determinante dieser
Matrix mit $\lambda$ multipliziert. Multipliziert man alle $n$ Zeilen der Matrix mit $\lambda$, so wird die
Determinante entsprechend mit $\lambda^n$ multipliziert, es gilt also

$ \begin{align}
    \mathrm{det} \, (\lambda \, \mathbf{A})
        \;=\; \lambda^n \, \mathrm{det} \, (\mathbf{A}) .
\end{align} $

In zwei Dimensionen entspricht die Determinante dem Flächeninhalt des Parallelogramms, welches
durch die beiden Spaltenvektoren der Matrix aufgespannt wird. Streckt man das Parallelogramm
mit $\lambda$, multipliziert sich sein Flächeninhalt mit dem Faktor $\lambda^2$.

In drei Dimensionen entspricht die Determinante dem Volumen des Spates, welcher durch die drei
Spaltenvektoren der Matrix aufgespannt wird. Streckt man diesen Spat mit $\lambda$, multipliziert
sich sein Rauminhalt mit dem Faktor $\lambda^3$

Oben genannte Rechenregel stimmt also gut mit der geometrischen Intuition überein.

## Aufgabe 5

Nein, denn im zweidimensionalen entspricht $-\mathbf{A}$ einer Multiplikation von $\mathbf{A}$ mit dem Faktor
$\lambda=-1$, die Determinante der negativen Matrix wird also mit $\lambda^2=1$ multipliziert und stimmt
damit mit der Determinante von $\mathbf{A}$ überein.

Im allgemeinen ist $\mathrm{det}\,(-\mathbf{A})=-\mathrm{det}\,(\mathbf{A})$ in allen Räumen mit ungerader
Dimension richtig und in allen Räumen mit gerader Dimension falsch.

## Aufgabe 6

Im Allgemeinen gilt der Multiplikationssatz für Determinanten:
    
$ \begin{align}
    \mathrm{det} \, (\mathbf{A} \cdot \mathbf {B})
        \;=\; \mathrm{det} \, (\mathbf{A}) \cdot \mathrm{det} \, (\mathbf{B}) .
\end{align} $

Ausserdem ist die Determinate der Einheitsmatrix $\mathrm{det} \, (\mathbf{I}) = 1$, also

$ \begin{align}
    \mathrm{det} \, (\mathbf{A}^{-1}) \cdot \mathrm{det} \, (\mathbf{A})
        \;=\; \mathrm{det} \, (\mathbf{A}^{-1} \cdot \mathbf{A})
        \;=\; \mathrm{det} \, (\mathbf{I})
        \;=\; 1
    \quad\Rightarrow\quad 
        \mathrm{det} \, (\mathbf{A}^{-1}) \;=\; \frac{1}{\mathrm{det} \, (\mathbf{A})} .
\end{align} $