In [1]:
import numpy as np

In [2]:
A = np.array ([
    [6, -1, -1],
    [1,  1, 10],
    [2, -1,  1.]
])
print (A)

[[ 6. -1. -1.]
 [ 1.  1. 10.]
 [ 2. -1.  1.]]


In [3]:
b = np.array ([
    [ 4],
    [-6],
    [-2.]
])
print (b)

[[ 4.]
 [-6.]
 [-2.]]


In [4]:
E21 = np.array ([
    [   1, 0, 0],
    [-1/6, 1, 0],
    [   0, 0, 1]
])
print (E21)

[[ 1.          0.          0.        ]
 [-0.16666667  1.          0.        ]
 [ 0.          0.          1.        ]]


In [5]:
print (E21 @ A)

[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 2.         -1.          1.        ]]


In [6]:
E31 = np.array ([
    [   1, 0, 0],
    [   0, 1, 0],
    [-1/3, 0, 1]
])
print (E31)

[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [-0.33333333  0.          1.        ]]


In [7]:
print (E31 @ E21 @ A)

[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 0.         -0.66666667  1.33333333]]


In [8]:
E32 = np.array ([
    [1,  0, 0],
    [0,  1, 0],
    [0,1/7, 1]
])
print (E32)

[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.14285714 1.        ]]


In [9]:
print (np.round (E32 @ E31 @ E21 @ A))

[[ 6. -1. -1.]
 [ 0.  1. 10.]
 [ 0. -0.  3.]]


In [10]:
U = E32 @ E31 @ E21 @ A
print (np.round (U, 10))

[[ 6.         -1.         -1.        ]
 [ 0.          1.16666667 10.16666667]
 [ 0.         -0.5         2.78571429]]


In [11]:
L = np.linalg.inv (E32 @ E31 @ E21)
print (L)

[[ 1.          0.          0.        ]
 [ 0.16666667  1.          0.        ]
 [ 0.33333333 -0.14285714  1.        ]]


In [12]:
print (L @ U)

[[ 6. -1. -1.]
 [ 1.  1. 10.]
 [ 2. -1.  1.]]


In [13]:
print (np.round (L @ U - A, 10))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
y = np.linalg.inv (L) @ b
print (y)

[[ 4.        ]
 [-6.66666667]
 [-4.28571429]]


In [15]:
x = np.linalg.inv (U) @ y
print (x)

[[ 1.]
 [ 3.]
 [-1.]]


In [16]:
print (A @ x)

[[ 4.]
 [-6.]
 [-2.]]


In [17]:
print (A @ x - b)

[[-1.77635684e-15]
 [-1.77635684e-15]
 [-1.33226763e-15]]
