In [1]:
import numpy as np

In [2]:
A = np.array ([
    [ 3, -6],
    [-2,  5]
])
print (A)

[[ 3 -6]
 [-2  5]]


In [3]:
b = np.array ([
    [0],
    [1]
])
print (b)

[[0]
 [1]]


In [4]:
E21 = np.array ([
    [  1, 0],
    [2/3, 1]
])
print (E21)

[[1.         0.        ]
 [0.66666667 1.        ]]


In [5]:
U = E21 @ A
print (U)

[[ 3. -6.]
 [ 0.  1.]]


In [6]:
L = np.linalg.inv (E21)
print (L)

[[ 1.          0.        ]
 [-0.66666667  1.        ]]


In [7]:
print (L @ U)

[[ 3. -6.]
 [-2.  5.]]


In [8]:
print (L @ U - A)

[[0. 0.]
 [0. 0.]]


In [9]:
y = np.linalg.inv (L) @ b
print (y)

[[0.]
 [1.]]


In [10]:
x = np.linalg.inv (U) @ y
print (x)

[[2.]
 [1.]]


In [11]:
print (A @ x)

[[0.]
 [1.]]


In [12]:
print (A @ x - b)

[[0.]
 [0.]]


In [13]:
print (A @ x - b)

[[0.]
 [0.]]
