In [13]:
import numpy as np

In [21]:
# müssen viel mehr Zeilen als Spalten haben, deshalb eventuell Transponation entfernen

xHat = np.array([
    [0, 1, 1, 2, 2, 3, 3, 4, 4, 5],
    [0, 1, 2, 1, 3, 2, 4, 3, 4, 5]
]).T
xHat

array([[0, 0],
       [1, 1],
       [1, 2],
       [2, 1],
       [2, 3],
       [3, 2],
       [3, 4],
       [4, 3],
       [4, 4],
       [5, 5]])

In [23]:
m = xHat.shape[0]
M = np.eye(m) - (1/m) * np.full((m, m), 1)
M

array([[ 0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9, -0.1],
       [-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1,  0.9]])

In [20]:
X = M @ xHat
X 

array([[-2.5, -2.5],
       [-1.5, -1.5],
       [-1.5, -0.5],
       [-0.5, -1.5],
       [-0.5,  0.5],
       [ 0.5, -0.5],
       [ 0.5,  1.5],
       [ 1.5,  0.5],
       [ 1.5,  1.5],
       [ 2.5,  2.5]])

In [25]:
C = (1 / (m -1)) * X.T @ X
C

array([[2.5       , 2.16666667],
       [2.16666667, 2.5       ]])