# Einfache Lineare Regression

A    -> Matrix der Beobachtungen mit einer Spalte von einsen am Anfang
b    -> Zielgrössen der Beobachtungen
e    -> Fehlervektor
xhat -> Lösung des Regressionsproblems (Regressionskoeffizienten)

Projektionsmatrix (P)

In [41]:
import numpy as np
import numpy.linalg as lg

A = np.array([
    [1, 0],
    [1, 1],
    [1, 2],
    [1, 3]
])

b = np.array([
    [1],
    [2],
    [2],
    [3]
])

In [52]:
A

array([[1, 1, 1],
       [1, 1, 2],
       [1, 2, 2],
       [1, 2, 1]])

In [53]:
b

array([[1],
       [2],
       [2],
       [3]])

In [42]:
ATA = (A.T @ A)
ATA

array([[ 4,  6],
       [ 6, 14]])

In [43]:
ATAinv = lg.inv(ATA)

In [44]:
xhat = ATAinv @ A.T @ b
xhat

array([[1.1],
       [0.6]])

In [46]:
P = A @ lg.inv((A.T @ A)) @ A.T
P

array([[ 0.7,  0.4,  0.1, -0.2],
       [ 0.4,  0.3,  0.2,  0.1],
       [ 0.1,  0.2,  0.3,  0.4],
       [-0.2,  0.1,  0.4,  0.7]])

In [48]:
regression_line = f"{xhat[0]} + {xhat[1]} * t"
regression_line

'[1.1] + [0.6] * t'

# Multiple Lineare Regression

A = Datenmatrix mit einer Spalte am Anfang
y = Matrix der Zielgrössen
b = Lösungsvektor des Regressionsproblems
yhat = Prädiktionsvektor & Projektionsvektor

In [100]:
import numpy as np
import numpy.linalg as lg

A = np.array([
    [1, 1, 1],
    [1, 2, 1],
    [1, 2, 2],
    [1, 1, 2],
])

y = np.array([
    [1],
    [2],
    [3],
    [3]
])

In [101]:
A

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 1, 2]])

In [102]:
y

array([[1],
       [2],
       [3],
       [3]])

In [103]:
ATA = A.T @ A
ATA

array([[ 4,  6,  6],
       [ 6, 10,  9],
       [ 6,  9, 10]])

In [104]:
b = lg.inv(A.T @ A) @ A.T @ y
b

array([[-0.75],
       [ 0.5 ],
       [ 1.5 ]])

In [105]:
P = A @ lg.inv((A.T @ A)) @ A.T
P

array([[ 0.75,  0.25, -0.25,  0.25],
       [ 0.25,  0.75,  0.25, -0.25],
       [-0.25,  0.25,  0.75,  0.25],
       [ 0.25, -0.25,  0.25,  0.75]])

In [113]:
m = A.shape[0]
Q = (np.eye(m, m) - P)
Q

array([[ 0.25, -0.25,  0.25, -0.25],
       [-0.25,  0.25, -0.25,  0.25],
       [ 0.25, -0.25,  0.25, -0.25],
       [-0.25,  0.25, -0.25,  0.25]])

In [114]:
yhat = P @ y
yhat

array([[1.25],
       [1.75],
       [3.25],
       [2.75]])

In [116]:
e = Q @ y
e

array([[-0.25],
       [ 0.25],
       [-0.25],
       [ 0.25]])

In [159]:
m = A.shape[0]
M = np.eye(m) - (1/m) * np.full((m, m), 1)
M

array([[ 0.75, -0.25, -0.25, -0.25],
       [-0.25,  0.75, -0.25, -0.25],
       [-0.25, -0.25,  0.75, -0.25],
       [-0.25, -0.25, -0.25,  0.75]])

In [118]:
SQR = y.T @ Q @ y
SQR


array([[0.25]])

In [161]:
SQT = y.T @ M @ y
SQT

array([[2.75]])

In [163]:
R2 = SQR / SQT
R2

array([[0.09090909]])