## LU-Zerlegung 3x3

In [9]:
import numpy as np
import numpy.linalg as lg

Bei der Lösung eines Gleichungssystems mittels LR-Zerlegung, können die Zeilen nur zu Beginn mittels einer Multiplikation einer Pseudo-Matrix verschoben werden. Pseudo-Matrix -> Einheitsmatrix mit vertauschten Zeilen

In [17]:
A = np.array([
    [2, 6, 2, 2],
    [-3, -8, 0, 2],
    [4, 9, 2, 3]
])
A

array([[ 2,  6,  2,  2],
       [-3, -8,  0,  2],
       [ 4,  9,  2,  3]])

In [18]:
E21 = np.array([
    [1   , 0, 0],
    [1.5, 1, 0],
    [0   , 0, 1]
])

E21 @ A

array([[2., 6., 2., 2.],
       [0., 1., 3., 5.],
       [4., 9., 2., 3.]])

In [20]:
E31 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [-2, 0, 1]
])

E31 @ E21 @ A

array([[ 2.,  6.,  2.,  2.],
       [ 0.,  1.,  3.,  5.],
       [ 0., -3., -2., -1.]])

In [23]:
E32 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 3, 1]
])

R = E32 @ E31 @ E21 @ A
R

array([[ 2.,  6.,  2.,  2.],
       [ 0.,  1.,  3.,  5.],
       [ 0.,  0.,  7., 14.]])

In [25]:
L = lg.inv(E21) @ lg.inv(E31) @ lg.inv(E32)
L

array([[ 1. ,  0. ,  0. ],
       [-1.5,  1. ,  0. ],
       [ 2. , -3. ,  1. ]])

In [27]:
L @ R

array([[ 2.,  6.,  2.,  2.],
       [-3., -8.,  0.,  2.],
       [ 4.,  9.,  2.,  3.]])

Lösung des Gleichungssystems mit Ergebnisvektor b
- Ly = b
- Rx = y