In [4]:
import numpy as np
import numpy.linalg as lg

In [5]:
A = np.array([
    [2, 2],
    [1, 1]
])

In [6]:
lg.svd(A)

(array([[-0.89442719, -0.4472136 ],
        [-0.4472136 ,  0.89442719]]),
 array([3.16227766e+00, 1.10062118e-17]),
 array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]))

In [8]:
ATA = A.T @ A
ATA

array([[5, 5],
       [5, 5]])

In [9]:
AAT = A @ A.T
AAT

array([[8, 4],
       [4, 2]])